function rejectedPromise() {
    return new Promise((_, reject) => {
      setTimeout(() => {
        reject("Errore: La promessa Ã¨ stata rifiutata");
      }, 1000);
    });
  }
  
  rejectedPromise()
    .catch((error) => {
      console.error("Gestione dell'errore:", error);
    });